version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: unituser
      POSTGRES_PASSWORD: unitpass
      POSTGRES_DB: unitdb
    ports:
      - '5432:5432'
    volumes:
      - prisma-dev-db:/var/lib/postgresql/data

volumes:
  prisma-dev-db:
    name: unitconversion_postgres_data
