'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi';
export type Region = 'US' | 'UK' | 'Metric' | 'India';

interface LocalizationState {
  language: Language;
  region: Region;
}

interface LocalizationContextType extends LocalizationState {
  setLanguage: (lang: Language) => void;
  setRegion: (region: Region) => void;
  t: (key: string) => string;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'ConvertMaster',
    'nav.home': 'Home',
    'nav.common': 'Common',
    'nav.professional': 'Professional',
    'nav.lifestyle': 'Lifestyle',
    'nav.developer': 'Developer',
    'nav.utilities': 'Utilities',
    'nav.about': 'About Us',
    'nav.login': 'Log In',
    'nav.signup': 'Sign Up',
    'nav.search': 'Search...',
    'settings.language': 'Language',
    'settings.region': 'Region',
    'welcome.title': 'Unit Converter',
    'welcome.subtitle': 'Select a category from the menu to get started.',
    'home.title': 'ConvertMaster',
    'home.description': 'Free online unit converter for length, weight, temperature, speed, and more. Instantly convert metric to imperial units with our easy-to-use calculator.',
    'home.convert': 'Convert',
    'home.cta': 'Start Converting',
    'home.convertOf': 'Convert units of',
    'home.hero.title': 'The Ultimate Unit Converter',
    'home.hero.subtitle': 'Fast, accurate, and easy-to-use conversions for all your needs.',
    'home.search.placeholder': 'e.g., 10 kg to lbs',
    'home.popular.title': 'Popular Tools',
    'home.cm_to_mm': 'cm to mm',
    'home.cm_to_mm.desc': 'Length conversion',
    'home.json_formatter': 'JSON Formatter',
    'home.json_formatter.desc': 'Format & validate',
    'home.base64_encoder': 'Base64 Encoder',
    'home.base64_encoder.desc': 'Encode & decode',
    'home.age_calculator': 'Age Calculator',
    'home.age_calculator.desc': 'Calculate age',
    'devtools.title': 'Developer Tools',
    'devtools.subtitle': 'Free online tools for web development and programming. Professional utilities for developers.',
    'devtools.smart_features': 'Smart Features',
    'devtools.smart_desc': 'Auto-convert, syntax highlighting, error detection, and batch processing.',
    'devtools.json_formatter': 'JSON Formatter',
    'devtools.json_formatter.desc': 'Format, validate, and beautify JSON with syntax highlighting and error detection',
    'devtools.base64_encoder': 'Base64 Encoder',
    'devtools.base64_encoder.desc': 'Encode and decode Base64 with file upload support and image preview',
    'devtools.url_encoder': 'URL Encoder',
    'devtools.url_encoder.desc': 'Encode and decode URLs with character reference and analysis tools',
    'devtools.timestamp_converter': 'Timestamp Converter',
    'devtools.timestamp_converter.desc': 'Convert Unix timestamps to human-readable dates with timezone support',
    'devtools.use_tool': 'Use Tool',
    'devtools.why_choose': 'Why Choose Our Developer Tools?',
    'devtools.fast_title': 'Lightning Fast',
    'devtools.fast_desc': 'Instant processing with no server delays',
    'devtools.secure_title': 'Secure & Private',
    'devtools.secure_desc': 'All processing happens in your browser',
    'devtools.professional_title': 'Professional Quality',
    'devtools.professional_desc': 'Enterprise-grade tools with advanced features',
    'devtools.trusted_title': 'Trusted by Developers',
    'devtools.daily_users': 'Daily Users',
    'devtools.conversions': 'Conversions',
    'devtools.uptime': 'Uptime',
    'json.title': 'JSON Formatter & Validator',
    'json.subtitle': 'Format, validate, and beautify JSON instantly. Free online tool with syntax highlighting.',
    'json.smart_features': 'Smart Features',
    'json.smart_desc': 'Auto-format, error detection, syntax highlighting, and collapse/expand support.',
    'json.input_label': 'Input JSON',
    'json.output_label': 'Formatted Output',
    'json.input_placeholder': '{"key": "value"}',
    'json.output_placeholder': 'Formatted JSON will appear here...',
    'json.copy': 'Copy',
    'json.copied': 'Copied!',
    'json.download': 'Download',
    'json.minify': 'Minify',
    'json.beautify': 'Beautify',
    'json.clear': 'Clear',
    'json.examples': 'Examples',
    'json.user_profile': 'User Profile',
    'json.user_profile_desc': 'User data with nested objects',
    'json.api_response': 'API Response',
    'json.api_response_desc': 'Sample API response format',
    'json.config_file': 'Config File',
    'json.config_file_desc': 'Application configuration',
    'json.copy_success': '✅ JSON copied to clipboard!',
    'json.copy_result': 'Copy result',
    'json.formatted_json': 'Formatted JSON',
    'json.auto_format': 'Auto Format',
    'json.auto_format_desc': 'Automatically formats JSON as you type',
    'json.error_detection': 'Error Detection',
    'json.error_detection_desc': 'Highlights syntax errors instantly',
    'json.syntax_highlighting': 'Syntax Highlighting',
    'json.syntax_highlighting_desc': 'Color-coded JSON for better readability',
    'json.minify_beautify': 'Minify & Beautify',
    'json.minify_beautify_desc': 'Toggle between compact and pretty formats',
    'json.share': 'Share',
    'base64.title': 'Base64 Encoder & Decoder',
    'base64.subtitle': 'Encode and decode Base64 instantly. Free online tool for text, files, and images.',
    'base64.smart_features': 'Smart Features',
    'base64.smart_desc': 'Text encoding, file upload, image preview, and automatic detection.',
    'base64.encode': 'Encode',
    'base64.decode': 'Decode',
    'base64.swap': 'Swap',
    'base64.input_text': 'Input',
    'base64.base64_input': 'Base64 Input',
    'base64.base64_output': 'Base64 Output',
    'base64.decoded_output': 'Decoded Output',
    'base64.text_input_placeholder': 'Enter text to encode...',
    'base64.base64_input_placeholder': 'Enter Base64 to decode...',
    'base64.output_placeholder': 'Base64 result will appear here...',
    'base64.decoded_placeholder': 'Decoded result will appear here...',
    'base64.upload_file': 'Upload a file to encode',
    'base64.upload_file_decode': 'Upload a file to decode',
    'base64.copy': 'Copy',
    'base64.copied': 'Copied!',
    'base64.download': 'Download',
    'base64.clear': 'Clear',
    'base64.share': 'Share',
    'base64.text_mode': 'Text',
    'base64.file_mode': 'File',
    'base64.copy_success': '✅ Base64 encoded text copied to clipboard!',
    'base64.decode_copy_success': '✅ Base64 decoded text copied to clipboard!',
    'base64.encoded': 'Encoded',
    'base64.decoded': 'Decoded',
    'base64.encoder': 'Encoder',
    'base64.decoder': 'Decoder',
    'base64.link_copied': 'Link Copied!',
    'base64.text_mode_button': 'Text',
    'base64.file_mode_button': 'File',
    'base64.upload_button': 'Upload',
    'base64.clear_button': 'Clear',
    'base64.load_examples': 'Load Examples',
    'base64.plain_text': 'Plain Text',
    'base64.plain_text_desc': 'Simple text example',
    'base64.json_data': 'JSON Data',
    'base64.json_data_desc': 'JSON object example',
    'base64.url_example': 'URL Example',
    'base64.url_example_desc': 'URL encoding example',
    'base64.xml_data': 'XML Data',
    'base64.xml_data_desc': 'XML document example',
    'url.title': 'URL Encoder & Decoder',
    'url.subtitle': 'Encode and decode URLs instantly. Free online URL encoder/decoder with character reference analysis.',
    'url.smart_features': 'Smart Features',
    'url.smart_desc': 'Character encoding, reference detection, and batch processing.',
    'url.encode': 'Encode',
    'url.decode': 'Decode',
    'url.input_label': 'Input URL',
    'url.output_label': 'Encoded/Decoded URL',
    'url.input_placeholder': 'Enter URL to encode...',
    'url.output_placeholder': 'Result will appear here...',
    'url.copy': 'Copy',
    'url.copied': 'Copied!',
    'url.clear': 'Clear',
    'url.share': 'Share',
    'url.load_examples': 'Load Examples',
    'url.simple_url': 'Simple URL',
    'url.simple_url_desc': 'Basic URL example',
    'url.query_params': 'Query Parameters',
    'url.query_params_desc': 'URL with parameters',
    'url.special_chars': 'Special Characters',
    'url.special_chars_desc': 'URL with special chars',
    'url.what_is_encoding': 'What is URL Encoding?',
    'url.what_is_encoding_desc': 'URL encoding (also known as percent encoding) converts special characters into a format that can be safely transmitted over the internet. Characters that are not allowed in URLs are replaced with a % followed by two hexadecimal digits.',
    'url.use_cases': 'Common Use Cases:',
    'url.use_case_1': 'Query parameters in URLs',
    'url.use_case_2': 'Form data submission',
    'url.use_case_3': 'API requests',
    'url.use_case_4': 'File uploads',
    'url.use_case_5': 'Search queries',
    'url.characters_encoding': 'Characters That Need Encoding:',
    'url.space': 'Space',
    'url.question_mark': 'Question mark',
    'url.ampersand': 'Ampersand',
    'url.equals': 'Equals',
    'url.hash': 'Hash',
    'url.plus': 'Plus',
    'url.invalid_format': 'Invalid URL format',
    'url.full_url': 'Full URL',
    'url.complete_url_example': 'Complete URL example',
    'url.analysis': 'URL Analysis',
    'timestamp.title': 'Timestamp Converter',
    'timestamp.subtitle': 'Convert Unix timestamps to human-readable dates and vice versa. Free online tool with timezone support.',
    'timestamp.smart_features': 'Smart Features',
    'timestamp.smart_desc': 'Multiple timezone support, current time display, and batch conversion.',
    'timestamp.convert': 'Convert',
    'timestamp.current_time': 'Current Time',
    'timestamp.timezone': 'Timezone',
    'timestamp.copy': 'Copy',
    'timestamp.copied': 'Copied!',
    'timestamp.clear': 'Clear',
    'timestamp.share': 'Share',
    'timestamp.load_examples': 'Load Examples',
    'timestamp.now': 'Now',
    'timestamp.yesterday': 'Yesterday',
    'timestamp.last_week': 'Last Week',
    'timestamp.custom': 'Custom',
    'timestamp.what_is': 'What is a Unix Timestamp?',
    'timestamp.what_is_desc': 'A Unix timestamp (also known as Unix time or epoch time) is a system for describing a point in time. It represents the number of seconds that have elapsed since 00:00:00 UTC on 1 January 1970 (the Unix epoch).',
    'timestamp.use_cases': 'Common Use Cases:',
    'timestamp.use_case_1': 'Programming and software development',
    'timestamp.use_case_2': 'Database record timestamps',
    'timestamp.use_case_3': 'API responses and requests',
    'timestamp.use_case_4': 'Log file entries',
    'timestamp.use_case_5': 'System time tracking',
    'timestamp.examples': 'Timestamp Examples:',
    'timestamp.example_1': 'January 1, 1970 00:00:00 UTC',
    'timestamp.example_2': 'January 1, 2000 00:00:00 UTC',
    'timestamp.example_3': 'January 1, 2020 00:00:00 UTC',
    'timestamp.example_current': 'Current time',
    'timestamp.example_current_desc': 'Varies (updates every second)',
    'age.title': 'Age Calculator',
    'age.subtitle': 'Calculate your exact age in years, months, days, hours, minutes, and seconds. Free online age calculator with birthday countdown.',
    'age.smart_features': 'Smart Features',
    'age.smart_desc': 'Precise calculation, birthday countdown, and milestone tracking.',
    'age.calculate': 'Calculate Age',
    'age.date_of_birth': 'Date of Birth',
    'age.current_date': 'Current Date',
    'age.years': 'Years',
    'age.months': 'Months',
    'age.days': 'Days',
    'age.hours': 'Hours',
    'age.minutes': 'Minutes',
    'age.seconds': 'Seconds',
    'age.copy': 'Copy',
    'age.copied': 'Copied!',
    'age.clear': 'Clear',
    'age.share': 'Share',
    'age.load_examples': 'Load Examples',
    'age.today': 'Today',
    'age.last_year': 'Last Year',
    'age.decade_ago': 'Decade Ago',
    'categories.title': 'Unit Categories',
    'categories.length': 'Length Converter',
    'categories.weight': 'Weight Converter',
    'categories.temperature': 'Temperature Converter',
    'categories.area': 'Area Converter',
    'categories.volume': 'Volume Converter',
    'categories.time': 'Time Converter',
    'categories.speed': 'Speed Converter',
    'categories.data': 'Data Converter',
    'categories.analytics': 'Analytics',
    'categories.length_desc': 'Convert between meters, feet, inches, and more',
    'categories.weight_desc': 'Convert between kilograms, pounds, grams, and more',
    'categories.temperature_desc': 'Convert between Celsius, Fahrenheit, and Kelvin',
    'categories.area_desc': 'Convert between square meters, square feet, acres, and more',
    'categories.volume_desc': 'Convert between liters, gallons, milliliters, and more',
    'categories.time_desc': 'Convert between seconds, minutes, hours, days, and more',
    'categories.speed_desc': 'Convert between mph, km/h, m/s, and knots',
    'categories.data_desc': 'Convert between bytes, kilobytes, megabytes, and more',
    'utilities.title': 'Utilities',
    'utilities.subtitle': 'Free online utility tools for daily use and calculations. Essential tools for everyday life.',
    'utilities.age_calculator': 'Age Calculator',
    'utilities.age_calculator.desc': 'Calculate your exact age in years, months, days with birthday countdown and milestones',
    'utilities.time_duration': 'Time Duration Calculator',
    'utilities.time_duration.desc': 'Calculate time differences between dates and track duration with precision',
    'utilities.percentage_calculator': 'Percentage Calculator',
    'utilities.percentage_calculator.desc': 'Calculate percentages, discounts, and ratios with easy-to-use interface',
    'utilities.interest_calculator': 'Interest Calculator',
    'utilities.interest_calculator.desc': 'Calculate simple and compound interest for loans and investments',
    'utilities.tip_calculator': 'Tip Calculator',
    'utilities.tip_calculator.desc': 'Calculate tips and split bills with ease',
    'utilities.use_tool': 'Use Tool',
    'utilities.why_choose': 'Why Choose Our Utilities?',
    'utilities.daily_title': 'Daily Life Tools',
    'utilities.daily_desc': 'Essential tools designed for everyday calculations and tasks',
    'utilities.accurate_title': 'Highly Accurate',
    'utilities.accurate_desc': 'Precise calculations with reliable algorithms',
    'utilities.simple_title': 'Simple to Use',
    'utilities.simple_desc': 'Clean interface with step-by-step guidance',
    'utilities.free_title': 'Always Free',
    'utilities.free_desc': 'No registration or fees required',
    'utilities.trusted_title': 'Trusted by Users',
    'utilities.daily_users': 'Daily Users',
    'utilities.calculations': 'Calculations',
    'utilities.satisfaction': 'Satisfaction',
    'category.length': 'Length',
    'category.weight': 'Weight',
    'category.temperature': 'Temperature',
    'category.area': 'Area',
    'category.volume': 'Volume',
    'category.time': 'Time',
    'category.speed': 'Speed',
    'category.data': 'Data',
    'category.analytics': 'Analytics',
    'category.dev-tools': 'Developer Tools',
    'category.utilities': 'Utilities',
    // Units (English)
    'unit.m': 'Meter',
    'unit.km': 'Kilometer',
    'unit.cm': 'Centimeter',
    'unit.mm': 'Millimeter',
    'unit.mi': 'Mile',
    'unit.yd': 'Yard',
    'unit.ft': 'Foot',
    'unit.in': 'Inch',
    'unit.kg': 'Kilogram',
    'unit.g': 'Gram',
    'unit.lb': 'Pound',
    'unit.oz': 'Ounce',
    'unit.c': 'Celsius',
    'unit.f': 'Fahrenheit',
    'unit.k': 'Kelvin',
    'unit.sq_m': 'Square Meter',
    'unit.sq_km': 'Square Kilometer',
    'unit.sq_ft': 'Square Foot',
    'unit.sq_in': 'Square Inch',
    'unit.l': 'Liter',
    'unit.ml': 'Milliliter',
    'unit.gal': 'Gallon',
    'unit.cu_m': 'Cubic Meter',
    'unit.cu_ft': 'Cubic Foot',
    'unit.cu_in': 'Cubic Inch',
    'unit.s': 'Second',
    'unit.min': 'Minute',
    'unit.h': 'Hour',
    'unit.day': 'Day',
    'unit.ms': 'Millisecond',
    'unit.mph': 'Miles per Hour',
    'unit.kmph': 'Kilometers per Hour',
    'unit.mps': 'Meters per Second',
    'unit.knot': 'Knot',
    'unit.b': 'Byte',
    'unit.kb': 'Kilobyte',
    'unit.mb': 'Megabyte',
    'unit.gb': 'Gigabyte',
    'unit.tb': 'Terabyte',
    'unit.pb': 'Petabyte',
    'unit.ratti': 'Ratti',
    'unit.maund': 'Maund',
    'unit.quintal': 'Quintal',
    'unit.bigha': 'Bigha',
    'unit.guntha': 'Guntha',
    'unit.biswa': 'Biswa',
    'unit.kanal': 'Kanal',
    'unit.marla': 'Marla',
    'unit.ground': 'Ground',
    'unit.cent': 'Cent',
    // Analytics MVP
    'analytics.mvp.title': 'Analytics Dashboard',
    'analytics.mvp.subtitle': 'Track your conversion patterns, analyze usage trends, and optimize your workflow with powerful insights',
    'analytics.mvp.conversions': 'Conversions Tracked',
    'analytics.mvp.avg_time': 'Average Response Time',
    'analytics.mvp.accuracy': 'Accuracy Rate',
    'analytics.mvp.cta': 'Explore Analytics',
    'analytics.mvp.cta_desc': 'Get detailed insights about your conversion patterns',
    'analytics.title': 'Conversion Analytics',
    'analytics.subtitle': 'Track your conversion history and usage statistics',
    'analytics.total_conversions': 'Total Conversions',
    'analytics.top_category': 'Top Category',
    'analytics.top_unit': 'Top Unit',
    'analytics.per_day': 'Per Day',
    'analytics.peak_hour': 'Peak Hour',
    'analytics.favorite': 'Favorite',
    'analytics.loading': 'Loading analytics...',
    'analytics.about_title': 'About Conversion History',
    'analytics.about_desc': 'Your conversion history is stored locally in your browser. No data is sent to any server.',
    'analytics.clear_confirm': 'Are you sure you want to clear all conversion history? This cannot be undone.',
    'analytics.download_file': 'conversion-history.json',
    // Converter Interface
    'converter.title': 'Converter',
    'converter.from': 'From',
    'converter.to': 'To',
    'converter.value': 'Amount',
    'converter.convert': 'Convert',
    'converter.result': 'Result',
    'converter.formula': 'Formula',
    'converter.copy': 'Copy',
    'converter.copied': 'Copied!',
    'converter.swap': 'Swap',
    'converter.select_unit': 'Select Unit',
    'converter.placeholder': '100',
    'converter.result_placeholder': '👉 Enter a value above and click Convert',
    'converter.error': 'Error',
    'converter.validation.empty': 'Please enter a value',
    'converter.validation.invalid': 'Numbers only',
    'url.encode_error': 'Invalid input for encoding',
    'url.decode_error': 'Invalid input for decoding',
    // SEO Content
    'seo.title': 'About ConvertMaster',
    'seo.description': 'Welcome to ConvertMaster, your free online calculator and conversion tool. Instantly convert between metric and imperial units for length, weight, temperature, and more.',
    'seo.keywords': 'Our measurement converter is designed for accuracy and ease of use. Whether you need to convert metric to imperial or imperial to metric, our tool handles it all.',
    'about.title': 'About ConvertMaster',
    'about.intro': 'ConvertMaster makes unit conversions fast, simple, and reliable. Convert common and specialized units across categories like length, weight, temperature, volume, and data with a single, easy-to-use tool.',
    'about.mission.title': 'Our Mission',
    'about.mission': "Our mission is to be the web's most trusted and user-friendly unit converter. We are dedicated to empowering our users with a powerful, accessible, and completely free tool for all their conversion needs. We continuously update our converter to include new units and categories, ensuring accuracy and relevance. We are committed to providing a seamless experience on any device, helping you convert units effortlessly, whether you're at your desk or on the go. Our goal is to be your go-to resource for any conversion, big or small.",
    'about.features': "Discover the power of our ConvertMaster. Our platform offers a simple, clean, and responsive design that works flawlessly on desktops, tablets, and mobile devices. With a vast database of units, you can convert everything from speed (mph to km/h) and volume (gallons to liters) to more niche measurements in fields like healthcare and construction. We prioritize accuracy and speed, delivering results you can trust in a fraction of a second. Bookmark our site for a one-click solution to all your unit conversion challenges and see why millions of users are making us their preferred online converter.",
    'about.why.title': 'Why Choose Us?',
    'about.why.choose.convertmaster': 'Why Choose ConvertMaster?',
    'about.cta.ready': 'Ready to Transform How You Convert?',
    'about.cta.ready.desc': 'Join millions of users who trust ConvertMaster for fast, accurate, and reliable unit conversions every single day.',
    'about.trusted.worldwide': 'TRUSTED WORLDWIDE',
    'about.accuracy.title': 'Accuracy',
    'about.accuracy.desc': 'Our conversion algorithms are rigorously tested to ensure you get the most accurate and reliable results every time.',
    'about.speed.title': 'Speed',
    'about.speed.desc': 'Get instant conversions with our lightning-fast interface, designed to provide immediate results without any delay.',
    'about.userfriendly.title': 'User-Friendly',
    'about.userfriendly.desc': 'With a clean, intuitive, and mobile-friendly design, our tool is easy to use for anyone, on any device.',
    'about.cta.title': 'Ready to Get Started?',
    'about.cta.desc': 'Select a category from the menu and start converting!',
    'about.cta.button': 'Go to Converter',
    'features.instant.title': 'Instant Results',
    'features.instant.desc': 'Get real-time conversions as you type with high precision algorithms.',
    'features.comprehensive.title': 'Comprehensive',
    'features.comprehensive.desc': 'Support for common, professional, and lifestyle units across many categories.',
    'features.customizable.title': 'Customizable',
    'features.customizable.desc': 'Localized experience with region and language settings to fit your needs.',
    'ad.space': 'Advertisement Space',
    'footer.description': 'The most accurate and easy-to-use conversion tool for all your needs. Built with modern web technologies for speed and reliability.',
    'footer.product': 'Product',
    'footer.converters': 'Converters',
    'footer.features': 'Features',
    'footer.api': 'API (Coming Soon)',
    'footer.company': 'Company',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    // Auth
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to your account to continue',
    'auth.email': 'Email Address',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.forgot_password': 'Forgot Password?',
    'auth.login.button': 'Log In',
    'auth.no_account': "Don't have an account?",
    'auth.signup.subtitle': 'Join us to access all features',
    'auth.name': 'Full Name',
    'auth.confirm_password': 'Confirm Password',
    'auth.signup.button': 'Sign Up',
    'auth.has_account': 'Already have an account?',
  },
  hi: {
    'app.title': 'कन्वर्ट मास्टर',
    'nav.home': 'होम',
    'nav.common': 'सामान्य',
    'nav.professional': 'पेशेवर',
    'nav.lifestyle': 'जीवन शैली',
    'nav.developer': 'डेवलपर',
    'nav.utilities': 'उपयोगिताएं',
    'nav.about': 'हमारे बारे में',
    'nav.login': 'लॉग इन',
    'nav.signup': 'साइन अप',
    'nav.search': 'खोजें...',
    'settings.language': 'भाषा',
    'settings.region': 'क्षेत्र',
    'welcome.title': 'इकाई परिवर्तक',
    'welcome.subtitle': 'शुरू करने के लिए मेनू से एक श्रेणी चुनें।',
    'home.title': 'यूनिवर्सल कन्वर्टर',
    'home.description': 'लंबाई, वजन, तापमान और अधिक के लिए मुफ्त ऑनलाइन यूनिट कन्वर्टर। हमारे आसान कैलकुलेटर के साथ तुरंत मीट्रिक को इंपीरियल इकाइयों में बदलें।',
    'home.convert': 'बदलें',
    'home.cta': 'कन्वर्ट करना शुरू करें',
    'home.convertOf': 'की इकाइयों को बदलें',
    'home.hero.title': 'अंतिम यूनिट कन्वर्टर',
    'home.hero.subtitle': 'आपकी सभी जरूरतों के लिए तेज, सटीक और उपयोग में आसान रूपांतरण।',
    'home.search.placeholder': 'उदाहरण के लिए, 10 किग्राम से पाउंड',
    'home.popular.title': 'लोकप्रिय उपकरण',
    'home.cm_to_mm': 'सेमी से मिमी',
    'home.cm_to_mm.desc': 'लंबाई रूपांतरण',
    'home.json_formatter': 'JSON फॉर्मेटर',
    'home.json_formatter.desc': 'फॉर्मेट और सत्यापन',
    'home.base64_encoder': 'Base64 एनकोडर',
    'home.base64_encoder.desc': 'एनकोड और डिकोड',
    'home.age_calculator': 'आयु कैलकुलेटर',
    'home.age_calculator.desc': 'आयु की गणना करें',
    'devtools.title': 'डेवलपर टूल्स',
    'devtools.subtitle': 'वेब विकास और प्रोग्रामिंग के लिए मुफ्त ऑनलाइन उपकरण। डेवलपर्स के लिए पेशेवर उपयोगिताएं।',
    'devtools.smart_features': 'स्मार्ट फीचर्स',
    'devtools.smart_desc': 'ऑटो-कन्वर्ट, सिंटैक्स हाइलाइटिंग, एरर डिटेक्शन, और बैच प्रोसेसिंग।',
    'devtools.json_formatter': 'JSON फॉर्मेटर',
    'devtools.json_formatter.desc': 'सिंटैक्स हाइलाइटिंग और एरर डिटेक्शन के साथ JSON को फॉर्मेट, सत्यापित और सुंदर बनाएं',
    'devtools.base64_encoder': 'Base64 एनकोडर',
    'devtools.base64_encoder.desc': 'फाइल अपलोड समर्थन और छवि पूर्वावलोकन के साथ Base64 एनकोड और डिकोड करें',
    'devtools.url_encoder': 'URL एनकोडर',
    'devtools.url_encoder.desc': 'कैरेक्टर रेफरेंस और विश्लेषण उपकरणों के साथ URL एनकोड और डिकोड करें',
    'devtools.timestamp_converter': 'टाइमस्टैम्प कन्वर्टर',
    'devtools.timestamp_converter.desc': 'टाइमजोन समर्थन के साथ यूनिक्स टाइमस्टैम्प को मानव-पठनीय दिनांक में बदलें',
    'devtools.use_tool': 'उपकरण का उपयोग करें',
    'devtools.why_choose': 'हमारे डेवलपर टूल्स क्यों चुनें?',
    'devtools.fast_title': 'बिजली की तेजी',
    'devtools.fast_desc': 'कोई सर्वर देरी के बिना तत्काल प्रोसेसिंग',
    'devtools.secure_title': 'सुरक्षित और निजी',
    'devtools.secure_desc': 'सभी प्रोसेसिंग आपके ब्राउज़र में होती है',
    'devtools.professional_title': 'पेशेवर गुणवत्ता',
    'devtools.professional_desc': 'उन्नत फीचर्स के साथ एंटरप्राइज़-ग्रेड उपकरण',
    'devtools.trusted_title': 'डेवलपर्स द्वारा विश्वसनीय',
    'devtools.daily_users': 'दैनिक उपयोगकर्ता',
    'devtools.conversions': 'रूपांतरण',
    'devtools.uptime': 'अपटाइम',
    'json.title': 'JSON फॉर्मेटर और वैलिडेटर',
    'json.subtitle': 'JSON को तुरंत फॉर्मेट, सत्यापित और सुंदर बनाएं। सिंटैक्स हाइलाइटिंग के साथ मुफ्त ऑनलाइन टूल।',
    'json.smart_features': 'स्मार्ट फीचर्स',
    'json.smart_desc': 'ऑटो-फॉर्मेट, एरर डिटेक्शन, सिंटैक्स हाइलाइटिंग, और कोलैप्स/एक्सपांड समर्थन।',
    'json.input_label': 'इनपुट JSON',
    'json.output_label': 'फॉर्मेटेड आउटपुट',
    'json.input_placeholder': '{"key": "value"}',
    'json.output_placeholder': 'फॉर्मेटेड JSON यहां दिखाई देगा...',
    'json.copy': 'कॉपी',
    'json.copied': 'कॉपी हो गया!',
    'json.download': 'डाउनलोड',
    'json.minify': 'छोटा करें',
    'json.beautify': 'सुंदर बनाएं',
    'json.clear': 'साफ करें',
    'json.examples': 'उदाहरण',
    'json.user_profile': 'उपयोगकर्ता प्रोफाइल',
    'json.user_profile_desc': 'नेस्टेड ऑब्जेक्ट्स के साथ उपयोगकर्ता डेटा',
    'json.api_response': 'API रिस्पांस',
    'json.api_response_desc': 'सैंपल API रिस्पांस फॉर्मेट',
    'json.config_file': 'कॉन्फिग फाइल',
    'json.config_file_desc': 'एप्लिकेशन कॉन्फिगरेशन',
    'json.copy_success': '✅ JSON क्लिपबोर्ड पर कॉपी हो गया!',
    'json.copy_result': 'परिणाम कॉपी करें',
    'json.formatted_json': 'फॉर्मेटेड JSON',
    'json.auto_format': 'ऑटो फॉर्मेट',
    'json.auto_format_desc': 'टाइप करते समय JSON स्वचालित रूप से फॉर्मेट होता है',
    'json.error_detection': 'त्रुटि पहचान',
    'json.error_detection_desc': 'सिंटैक्स त्रुटियों को तुरंत हाइलाइट करता है',
    'json.syntax_highlighting': 'सिंटैक्स हाइलाइटिंग',
    'json.syntax_highlighting_desc': 'बेहतर पठनीयता के लिए रंग-कोडेड JSON',
    'json.minify_beautify': 'मिनिफाई और सुंदर बनाएं',
    'json.minify_beautify_desc': 'कॉम्पैक्ट और सुंदर प्रारूपों के बीच टॉगल करें',
    'base64.title': 'Base64 एनकोडर और डिकोडर',
    'base64.subtitle': 'Base64 को तुरंत एनकोड और डिकोड करें। टेक्स्ट, फाइलों और छवियों के लिए मुफ्त ऑनलाइन टूल।',
    'base64.smart_features': 'स्मार्ट फीचर्स',
    'base64.smart_desc': 'टेक्स्ट एनकोडिंग, फाइल अपलोड, छवि पूर्वावलोकन, और स्वचालित डिटेक्शन।',
    'base64.encode': 'एनकोड',
    'base64.decode': 'डिकोड',
    'base64.swap': 'स्वैप',
    'base64.input_text': 'इनपुट',
    'base64.base64_input': 'Base64 इनपुट',
    'base64.base64_output': 'Base64 आउटपुट',
    'base64.decoded_output': 'डिकोडेड आउटपुट',
    'base64.text_input_placeholder': 'एनकोड करने के लिए टेक्स्ट दर्ज करें...',
    'base64.base64_input_placeholder': 'डिकोड करने के लिए Base64 दर्ज करें...',
    'base64.output_placeholder': 'Base64 परिणाम यहां दिखाई देगा...',
    'base64.decoded_placeholder': 'डिकोडेड परिणाम यहां दिखाई देगा...',
    'base64.upload_file': 'एनकोड करने के लिए फाइल अपलोड करें',
    'base64.upload_file_decode': 'डिकोड करने के लिए फाइल अपलोड करें',
    'base64.copy': 'कॉपी',
    'base64.copied': 'कॉपी हो गया!',
    'base64.download': 'डाउनलोड',
    'base64.clear': 'साफ करें',
    'base64.share': 'शेयर',
    'base64.text_mode': 'टेक्स्ट',
    'base64.file_mode': 'फाइल',
    'base64.copy_success': '✅ Base64 एनकोडेड टेक्स्ट क्लिपबोर्ड पर कॉपी हो गया!',
    'base64.decode_copy_success': '✅ Base64 डिकोडेड टेक्स्ट क्लिपबोर्ड पर कॉपी हो गया!',
    'base64.encoded': 'एनकोडेड',
    'base64.decoded': 'डिकोडेड',
    'base64.encoder': 'एनकोडर',
    'base64.decoder': 'डिकोडर',
    'base64.link_copied': 'लिंक कॉपी हो गया!',
    'base64.text_mode_button': 'टेक्स्ट',
    'base64.file_mode_button': 'फाइल',
    'base64.upload_button': 'अपलोड',
    'base64.clear_button': 'साफ करें',
    'base64.load_examples': 'उदाहरण लोड करें',
    'base64.plain_text': 'सादा टेक्स्ट',
    'base64.plain_text_desc': 'सरल टेक्स्ट उदाहरण',
    'base64.json_data': 'JSON डेटा',
    'base64.json_data_desc': 'JSON ऑब्जेक्ट उदाहरण',
    'base64.url_example': 'URL उदाहरण',
    'base64.url_example_desc': 'URL एनकोडिंग उदाहरण',
    'base64.xml_data': 'XML डेटा',
    'base64.xml_data_desc': 'XML दस्तावेज़ उदाहरण',
    'url.title': 'URL एनकोडर और डिकोडर',
    'url.subtitle': 'URL को तुरंत एनकोड और डिकोड करें। कैरेक्टर रेफरेंस विश्लेषण के साथ मुफ्त ऑनलाइन URL एनकोडर/डिकोडर।',
    'url.smart_features': 'स्मार्ट फीचर्स',
    'url.smart_desc': 'कैरेक्टर एनकोडिंग, रेफरेंस डिटेक्शन, और बैच प्रोसेसिंग।',
    'url.encode': 'एनकोड',
    'url.decode': 'डिकोड',
    'url.input_label': 'इनपुट URL',
    'url.output_label': 'एनकोडेड/डिकोडेड URL',
    'url.input_placeholder': 'एनकोड करने के लिए URL दर्ज करें...',
    'url.output_placeholder': 'परिणाम यहां दिखाई देगा...',
    'url.copy': 'कॉपी',
    'url.copied': 'कॉपी हो गया!',
    'url.clear': 'साफ करें',
    'url.share': 'शेयर',
    'url.load_examples': 'उदाहरण लोड करें',
    'url.simple_url': 'सिंपल URL',
    'url.simple_url_desc': 'बेसिक URL उदाहरण',
    'url.query_params': 'क्वेरी पैरामीटर्स',
    'url.query_params_desc': 'पैरामीटर्स के साथ URL',
    'url.special_chars': 'विशेष कैरेक्टर',
    'url.special_chars_desc': 'विशेष कैरेक्टर्स के साथ URL',
    'url.what_is_encoding': 'URL एनकोडिंग क्या है?',
    'url.what_is_encoding_desc': 'URL एनकोडिंग (जिसे प्रतिशत एनकोडिंग भी कहा जाता है) विशेष कैरेक्टर्स को एक ऐसे प्रारूप में कनवर्ट करता है जो इंटरनेट पर सुरक्षित रूप से भेजा जा सके। URLs में अनुमत नहीं वाले कैरेक्टर्स को % के साथ बदल दिया जाता है, उसके बाद दो हेक्साडेसिमल अंक।',
    'url.use_cases': 'सामान्य उपयोग के मामले:',
    'url.use_case_1': 'URL में क्वेरी पैरामीटर्स',
    'url.use_case_2': 'फॉर्म डेटा सबमिशन',
    'url.use_case_3': 'API अनुरोध',
    'url.use_case_4': 'फाइल अपलोड',
    'url.use_case_5': 'खोज क्वेरी',
    'url.characters_encoding': 'एनकोडिंग की आवश्यकता वाले कैरेक्टर्स:',
    'url.space': 'स्पेस',
    'url.question_mark': 'क्वेश्चन मार्क',
    'url.ampersand': 'एम्परसैंड',
    'url.equals': 'इक्वल्स',
    'url.hash': 'हैश',
    'url.plus': 'प्लस',
    'url.invalid_format': 'अमान्य URL प्रारूप',
    'url.full_url': 'पूर्ण URL',
    'url.complete_url_example': 'पूर्ण URL उदाहरण',
    'url.analysis': 'URL विश्लेषण',
    'timestamp.title': 'टाइमस्टैम्प कन्वर्टर',
    'timestamp.subtitle': 'यूनिक्स टाइमस्टैम्प को मानव-पठनीय दिनांक में और इसके विपरीत बदलें। टाइमजोन समर्थन के साथ मुफ्त ऑनलाइन टूल।',
    'timestamp.smart_features': 'स्मार्ट फीचर्स',
    'timestamp.smart_desc': 'एकाधिक टाइमजोन समर्थन, वर्तमान समय प्रदर्शन, और बैच रूपांतरण।',
    'timestamp.convert': 'बदलें',
    'timestamp.current_time': 'वर्तमान समय',
    'timestamp.timezone': 'टाइमजोन',
    'timestamp.copy': 'कॉपी',
    'timestamp.copied': 'कॉपी हो गया!',
    'timestamp.clear': 'साफ करें',
'timestamp.share': 'शेयर',
'timestamp.load_examples': 'उदाहरण लोड करें',
'timestamp.now': 'अभी',
'timestamp.yesterday': 'कल',
'timestamp.last_week': 'पिछले सप्ताह',
'timestamp.custom': 'कस्टम',
'timestamp.what_is': 'यूनिक्स टाइमस्टैम्प क्या है?',
'timestamp.what_is_desc': 'यूनिक्स टाइमस्टैम्प (जिसे यूनिक्स समय या एपोक समय भी कहा जाता है) समय के एक बिंदु का वर्णन करने के लिए एक सिस्टम है। यह 1 जनवरी 1970 को 00:00:00 UTC के बाद से बीते हुए सेकंड की संख्या का प्रतिनिधित्व करता है (यूनिक्स एपोक)।',
'timestamp.use_cases': 'सामान्य उपयोग के मामले:',
'timestamp.use_case_1': 'प्रोग्रामिंग और सॉफ्टवेयर विकास',
'timestamp.use_case_2': 'डेटाबेस रिकॉर्ड टाइमस्टैम्प',
'timestamp.use_case_3': 'API प्रतिक्रियाएं और अनुरोध',
'timestamp.use_case_4': 'लॉग फाइल प्रविष्टियां',
'timestamp.use_case_5': 'सिस्टम समय ट्रैकिंग',
'timestamp.examples': 'टाइमस्टैम्प उदाहरण:',
'timestamp.example_1': 'जनवरी 1, 1970 00:00:00 UTC',
'timestamp.example_2': 'जनवरी 1, 2000 00:00:00 UTC',
'timestamp.example_3': 'जनवरी 1, 2020 00:00:00 UTC',
'timestamp.example_current': 'वर्तमान समय',
'timestamp.example_current_desc': 'भिन्न (हर सेकंड अपडेट होता है)',
'age.title': 'आयु कैलकुलेटर',
'age.subtitle': 'वर्षों, महीनों, दिनों, घंटों, मिनटों और सेकंड में अपनी सटीक आयु की गणना करें। जन्मदिन काउंटडाउन के साथ मुफ्त ऑनलाइन आयु कैलकुलेटर।',
'age.smart_features': 'स्मार्ट फीचर्स',
'age.smart_desc': 'सटीक गणना, जन्मदिन काउंटडाउन, और मील के पत्थर ट्रैकिंग।',
'age.calculate': 'आयु की गणना करें',
    'age.date_of_birth': 'जन्म तिथि',
    'age.current_date': 'वर्तमान दिनांक',
    'age.years': 'वर्ष',
    'age.months': 'महीने',
    'age.days': 'दिन',
    'age.hours': 'घंटे',
    'age.minutes': 'मिनट',
    'age.seconds': 'सेकंड',
    'age.copy': 'कॉपी',
    'age.copied': 'कॉपी हो गया!',
    'age.clear': 'साफ करें',
    'age.share': 'शेयर',
    'age.load_examples': 'उदाहरण लोड करें',
    'age.today': 'आज',
    'age.last_year': 'पिछले साल',
    'age.decade_ago': 'दशक पहले',
    'categories.title': 'इकाई श्रेणियां',
    'categories.length': 'लंबाई कन्वर्टर',
    'categories.weight': 'वजन कन्वर्टर',
    'categories.temperature': 'तापमान कन्वर्टर',
    'categories.area': 'क्षेत्रफल कन्वर्टर',
    'categories.volume': 'आयतन कन्वर्टर',
    'categories.time': 'समय कन्वर्टर',
    'categories.speed': 'गति कन्वर्टर',
    'categories.data': 'डेटा कन्वर्टर',
    'categories.analytics': 'विश्लेषण',
    'categories.length_desc': 'मीटर, फुट, इंच और अधिक के बीच रूपांतरण करें',
    'categories.weight_desc': 'किलोग्राम, पाउंड, ग्राम और अधिक के बीच रूपांतरण करें',
    'categories.temperature_desc': 'सेल्सियस, फारेनहाइट और केल्विन के बीच रूपांतरण करें',
    'categories.area_desc': 'वर्ग मीटर, वर्ग फुट, एकड़ और अधिक के बीच रूपांतरण करें',
    'categories.volume_desc': 'लीटर, गैलन, मिलीलीटर और अधिक के बीच रूपांतरण करें',
    'categories.time_desc': 'सेकंड, मिनट, घंटे, दिन और अधिक के बीच रूपांतरण करें',
    'categories.speed_desc': 'mph, km/h, m/s और नॉट्स के बीच रूपांतरण करें',
    'categories.data_desc': 'बाइट्स, किलोबाइट्स, मेगाबाइट्स और अधिक के बीच रूपांतरण करें',
    'utilities.title': 'उपयोगिताएं',
    'utilities.subtitle': 'दैनिक उपयोग और गणनाओं के लिए मुफ्त ऑनलाइन उपयोगिता उपकरण। रोजमर्रा की जिंदगी के लिए आवश्यक उपकरण।',
    'utilities.age_calculator': 'आयु कैलकुलेटर',
    'utilities.age_calculator.desc': 'जन्मदिन काउंटडाउन और मील के पत्थर के साथ वर्षों, महीनों, दिनों में अपनी सटीक आयु की गणना करें',
    'utilities.time_duration': 'समय अवधि कैलकुलेटर',
    'utilities.time_duration.desc': 'तिथियों के बीच समय अंतर की गणना करें और परिशुद्धता के साथ अवधि ट्रैक करें',
    'utilities.percentage_calculator': 'प्रतिशत कैलकुलेटर',
    'utilities.percentage_calculator.desc': 'आसान-उपयोग इंटरफेस के साथ प्रतिशत, छूट और अनुपात की गणना करें',
    'utilities.interest_calculator': 'ब्याज कैलकुलेटर',
    'utilities.interest_calculator.desc': 'ऋण और निवेशों के लिए साधारण और चक्रवृद्धि ब्याज की गणना करें',
    'utilities.tip_calculator': 'टिप कैलकुलेटर',
    'utilities.tip_calculator.desc': 'टिप्स की गणना करें और बिल आसानी से विभाजित करें',
    'utilities.use_tool': 'उपकरण का उपयोग करें',
    'utilities.why_choose': 'हमारी उपयोगिताएं क्यों चुनें?',
    'utilities.daily_title': 'रोजमर्रा की जिंदगी के उपकरण',
    'utilities.daily_desc': 'रोजमर्रा की गणनाओं और कार्यों के लिए डिज़ाइन किए गए आवश्यक उपकरण',
    'utilities.accurate_title': 'अत्यधिक सटीक',
    'utilities.accurate_desc': 'विश्वसनीय एल्गोरिदम के साथ सटीक गणनाएं',
    'utilities.simple_title': 'उपयोग में आसान',
    'utilities.simple_desc': 'चरण-दर-चरण मार्गदर्शन के साथ साफ इंटरफेस',
    'utilities.free_title': 'हमेशा मुफ्त',
    'utilities.free_desc': 'रजिस्ट्रेशन या शुल्क की आवश्यकता नहीं',
    'utilities.trusted_title': 'उपयोगकर्ताओं द्वारा विश्वसनीय',
    'utilities.daily_users': 'दैनिक उपयोगकर्ता',
    'utilities.calculations': 'गणनाएं',
    'utilities.satisfaction': 'संतुष्टि',
    'category.length': 'लंबाई',
    'category.weight': 'वजन',
    'category.temperature': 'तापमान',
    'category.area': 'क्षेत्रफल',
    'category.volume': 'आयतन',
    'category.time': 'समय',
    'category.speed': 'गति',
    'category.data': 'डेटा',
    'category.engineering': 'इंजीनियरिंग',
    'category.construction': 'निर्माण',
    'category.logistics': 'रसद',
    'category.chemical': 'रसायन',
    'category.cooking': 'खाना पकाना',
    'category.healthcare': 'स्वास्थ्य सेवा',
    'category.analytics': 'विश्लेषण',
    'category.dev-tools': 'डेवलपर टूल्स',
    'category.utilities': 'उपयोगिताएं',
    // Units
    'unit.m': 'मीटर',
    'unit.km': 'किलोमीटर',
    'unit.cm': 'सेंटीमीटर',
    'unit.mm': 'मिलीमीटर',
    'unit.mi': 'मील',
    'unit.yd': 'गज (Yard)',
    'unit.ft': 'फुट',
    'unit.in': 'इंच',
    'unit.kg': 'किलोग्राम',
    'unit.g': 'ग्राम',
    'unit.mg': 'मिलीग्राम',
    'unit.lb': 'पाउंड',
    'unit.oz': 'औंस',
    'unit.c': 'सेल्सियस',
    'unit.f': 'फारेनहाइट',
    'unit.k': 'केल्विन',
    'unit.m2': 'वर्ग मीटर',
    'unit.ha': 'हेक्टेयर',
    'unit.km2': 'वर्ग किलोमीटर',
    'unit.ft2': 'वर्ग फुट',
    'unit.ac': 'एकड़',
    'unit.mi2': 'वर्ग मील',
    'unit.l': 'लीटर',
    'unit.ml': 'मिलीलीटर',
    'unit.m3': 'घन मीटर',
    'unit.gal': 'गैलन (US)',
    'unit.qt': 'क्वार्ट (US)',
    'unit.pt': 'पेंट (US)',
    'unit.cup': 'कप (US)',
    'unit.fl_oz': 'द्रव औंस (US)',
    'unit.tsp': 'चम्मच',
    'unit.tbsp': 'बड़ा चम्मच',
    'unit.s': 'सेकंड',
    'unit.min': 'मिनट',
    'unit.h': 'घंटा',
    'unit.d': 'दिन',
    'unit.wk': 'सप्ताह',
    'unit.mo': 'महीना',
    'unit.yr': 'वर्ष',
    'unit.m_s': 'मीटर/सेकंड',
    'unit.km_h': 'किलोमीटर/घंटा',
    'unit.mph': 'मील/घंटा',
    'unit.kn': 'नॉट',
    'unit.b': 'बिट',
    'unit.B': 'बाइट',
    'unit.KB': 'किलोबाइट',
    'unit.MB': 'मेगाबाइट',
    'unit.GB': 'गीगाबाइट',
    'unit.TB': 'टेराबाइट',
    'unit.Pa': 'पास्कल',
    'unit.bar': 'बार',
    'unit.psi': 'PSI',
    'unit.atm': 'वायुमंडल',
    'unit.N': 'न्यूटन',
    'unit.lbf': 'पाउंड-बल',
    'unit.mpg': 'मील/गैलन',
    // Indian Units
    'unit.gaj': 'गज',
    'unit.tola': 'तोला',
    'unit.ratti': 'रत्ती',
    'unit.maund': 'मन',
    'unit.quintal': 'क्विंटल',
    'unit.bigha': 'बीघा',
    'unit.guntha': 'गुंठा',
    'unit.biswa': 'बिस्वा',
    'unit.kanal': 'कनाल',
    'unit.marla': 'मरला',
    'unit.ground': 'ग्राउंड',
    'unit.cent': 'सेंट',
    // Analytics MVP
    'analytics.mvp.title': 'विश्लेषण डैशबोर्ड',
    'analytics.mvp.subtitle': 'अपने रूपांतरण पैटर्न को ट्रैक करें, उपयोग प्रवृत्तियों का विश्लेषण करें, और शक्तिशाली अंतर्दृष्टि के साथ अपने वर्कफ़्लो को अनुकूलित करें',
    'analytics.mvp.conversions': 'रूपांतरण ट्रैक किए गए',
    'analytics.mvp.avg_time': 'औसत प्रतिक्रिया समय',
    'analytics.mvp.accuracy': 'सटीकता दर',
    'analytics.mvp.cta': 'विश्लेषण देखें',
    'analytics.mvp.cta_desc': 'अपने रूपांतरण पैटर्न के बारे में विस्तृत अंतर्दृष्टि प्राप्त करें',
    // Converter Interface
    'converter.title': 'कन्वर्टर',
    'converter.from': 'से',
    'converter.to': 'में',
    'converter.value': 'राशि',
    'converter.convert': 'बदलें',
    'converter.result': 'परिणाम',
    'converter.formula': 'सूत्र',
    'converter.copy': 'कॉपी',
    'converter.copied': 'कॉपी कर लिया!',
    'converter.swap': 'बदलें',
    'converter.select_unit': 'इकाई चुनें',
    'converter.placeholder': 'मान दर्ज करें...',
    'converter.result_placeholder': 'परिणाम यहां दिखाई देगा...',
    'converter.error': 'त्रुटि',
    'url.encode_error': 'एनकोडिंग के लिए अमान्य इनपुट',
    'url.decode_error': 'डिकोडिंग के लिए अमान्य इनपुट',
    // SEO Content
    'seo.title': 'यूनिवर्सल यूनिट कन्वर्टर के बारे में',
    'seo.description': 'यूनिवर्सल यूनिट कन्वर्टर में आपका स्वागत है, जो आपका मुफ्त ऑनलाइन कैलकुलेटर और रूपांतरण उपकरण है। लंबाई, वजन, तापमान और अधिक के लिए मीट्रिक और इंपीरियल इकाइयों के बीच तुरंत रूपांतरण करें।',
    'seo.keywords': 'हमारा माप परिवर्तक सटीकता और उपयोग में आसानी के लिए डिज़ाइन किया गया है। चाहे आपको मीट्रिक से इंपीरियल या इंपीरियल से मीट्रिक में बदलने की आवश्यकता हो, हमारा टूल यह सब संभालता है।',
    'about.title': 'यूनिवर्सल यूनिट कन्वर्टर के बारे में',
    'about.intro': 'यूनिवर्सल यूनिट कन्वर्टर एक व्यापक उपकरण है जिसे यूनिट रूपांतरणों को सरल, तेज और सटीक बनाने के लिए डिज़ाइन किया गया है। चाहे आप छात्र हों, पेशेवर हों, या बस किसी रेसिपी को बदलने की आवश्यकता हो, हमने आपको कवर किया है।',
    'about.mission': 'हमारा मिशन आपकी सभी रूपांतरण आवश्यकताओं के लिए एक उपयोगकर्ता के अनुकूल इंटरफेस प्रदान करना है, जो मीट्रिक से इंपीरियल और यहां तक कि क्षेत्रीय इकाइयों तक की विस्तृत श्रृंखला का समर्थन करता है।',
    'about.mission.title': 'हमारा मिशन',
    'about.why.title': 'हमें क्यों चुनें?',
    'about.why.choose.convertmaster': 'कन्वर्ट मास्टर क्यों चुनें?',
    'about.cta.ready': 'बदलने के लिए तैयार हैं?',
    'about.cta.ready.desc': 'हर दिन तेज, सटीक और विश्वसनीय यूनिट रूपांतरणों के लिए कन्वर्ट मास्टर पर भरोसा करने वाले लाखों उपयोगकर्ताओं में शामिल हों।',
    'about.trusted.worldwide': 'विश्वभर में विश्वसनीय',
    'about.accuracy.title': 'सटीकता',
    'about.accuracy.desc': 'हमारे रूपांतरण एल्गोरिदम का कड़ाई से परीक्षण किया जाता है ताकि यह सुनिश्चित किया जा सके कि आपको हर बार सबसे सटीक और विश्वसनीय परिणाम मिलें।',
    'about.speed.title': 'गति',
    'about.speed.desc': 'हमारे बिजली की तेजी से इंटरफेस के साथ तत्काल रूपांतरण प्राप्त करें, जिसे बिना किसी देरी के तत्काल परिणाम प्रदान करने के लिए डिज़ाइन किया गया है।',
    'about.userfriendly.title': 'उपयोगकर्ता के अनुकूल',
    'about.userfriendly.desc': 'एक साफ, सहज और मोबाइल के अनुकूल डिजाइन के साथ, हमारा उपकरण किसी के लिए भी, किसी भी डिवाइस पर उपयोग करना आसान है।',
    'about.cta.title': 'शुरू करने के लिए तैयार हैं?',
    'about.cta.desc': 'मेनू से एक श्रेणी चुनें और कन्वर्ट करना शुरू करें!',
    'about.cta.button': 'कन्वर्टर पर जाएं',
    'features.instant.title': 'तत्काल परिणाम',
    'features.instant.desc': 'उच्च परिशुद्धता एल्गोरिदम के साथ टाइप करते ही वास्तविक समय में रूपांतरण प्राप्त करें।',
    'features.comprehensive.title': 'व्यापक',
    'features.comprehensive.desc': 'कई श्रेणियों में सामान्य, पेशेवर और जीवन शैली इकाइयों के लिए समर्थन।',
    'features.customizable.title': 'अनुकूलन योग्य',
    'features.customizable.desc': 'आपकी आवश्यकताओं के अनुरूप क्षेत्र और भाषा सेटिंग्स के साथ स्थानीयकृत अनुभव।',
    'ad.space': 'विज्ञापन स्थान',
    'footer.description': 'आपकी सभी आवश्यकताओं के लिए सबसे सटीक और उपयोग में आसान रूपांतरण उपकरण। गति और विश्वसनीयता के लिए आधुनिक वेब तकनीकों के साथ बनाया गया।',
    'footer.product': 'उत्पाद',
    'footer.converters': 'कन्वर्टर्स',
    'footer.features': 'विशेषताएं',
    'footer.api': 'एपीआई (जल्द आ रहा है)',
    'footer.company': 'कंपनी',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    // Auth
    'auth.login.title': 'वापसी पर स्वागत है',
    'auth.login.subtitle': 'जारी रखने के लिए अपने खाते में साइन इन करें',
    'auth.email': 'ईमेल पता',
    'auth.username': 'उपयोगकर्ता नाम',
    'auth.password': 'पासवर्ड',
    'auth.forgot_password': 'पासवर्ड भूल गए?',
    'auth.login.button': 'साइन इन करें',
    'auth.no_account': "खाता नहीं है?",
    'auth.signup.title': 'खाता बनाएं',
    'auth.signup.subtitle': 'सभी सुविधाओं का उपयोग करने के लिए हमसे जुड़ें',
    'auth.name': 'पूरा नाम',
    'auth.confirm_password': 'पासवर्ड की पुष्टि करें',
    'auth.signup.button': 'साइन अप करें',
    'auth.has_account': 'क्या आपके पास पहले से एक खाता है?',
  },
};

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const [region, setRegion] = useState<Region>('Metric');

  useEffect(() => {
    const savedLang = localStorage.getItem('unit-converter-lang') as Language;
    const savedRegion = localStorage.getItem('unit-converter-region') as Region;
    if (savedLang) setLanguage(savedLang);
    if (savedRegion) setRegion(savedRegion);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('unit-converter-lang', lang);
  };

  const handleSetRegion = (reg: Region) => {
    setRegion(reg);
    localStorage.setItem('unit-converter-region', reg);
  };

  const t = (key: string) => {
    return TRANSLATIONS[language]?.[key] || key;
  };

  return (
    <LocalizationContext.Provider
      value={{ language, region, setLanguage: handleSetLanguage, setRegion: handleSetRegion, t }}
    >
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};